name: tasks_api
description: Models and interfaces of TaskApi.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  uuid: ^3.0.6

dev_dependencies:
  test: ^1.20.2